apiVersion: v1
kind: Namespace
metadata:
  name: ldap

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ldap
  name: ldap
spec:
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: cjyar/openldap:2.4.50
          args:
            - -F
            - /config
            - -h
            - ldapi:/// ldap:/// ldaps:///
          livenessProbe:
            exec:
              command: [ "ldapsearch", "-H", "ldapi:///", "-Y", "EXTERNAL", "-b", "", "-s", "base", "(objectclass=*)", "namingContexts" ]
          ports:
          - containerPort: 389
            name: ldap
          - containerPort: 636
            name: ldaps
          volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /data
            name: data
      securityContext:
        fsGroup: 1001
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: openldap

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ldap
  name: openldap
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  namespace: ldap
  name: openldap
spec:
  type: LoadBalancer
  ports:
    - name: ldap
      port: 389
      targetPort: 1389
    - name: ldaps
      port: 636
      targetPort: 1636
  selector:
    app: openldap
